'------------------------------------------------------------------------------
' <auto-generated>
'     Tento kód byl generován nástrojem.
'     Verze modulu runtime:4.0.30319.42000
'
'     Změny tohoto souboru mohou způsobit nesprávné chování a budou ztraceny,
'     dojde-li k novému generování kódu.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Namespace TrackVideoExporter
    
    <Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(),
     Global.System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "17.14.0.0")>
    Partial Friend NotInheritable Class VideoExportSettings
        Inherits Global.System.Configuration.ApplicationSettingsBase

        Private Shared defaultInstance As VideoExportSettings = CType(Global.System.Configuration.ApplicationSettingsBase.Synchronized(New VideoExportSettings()), VideoExportSettings)

        Public Shared ReadOnly Property [Default]() As VideoExportSettings
            Get
                Return defaultInstance
            End Get
        End Property

        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property FfmpegPath() As String
            Get
                Return CType(Me("FfmpegPath"),String)
            End Get
            Set
                Me("FfmpegPath") = value
            End Set
        End Property
    End Class
End Namespace
