'------------------------------------------------------------------------------
' <auto-generated>
'     Tento kód byl generován nástrojem.
'     Verze modulu runtime:4.0.30319.42000
'
'     Změny tohoto souboru mohou způsobit nesprávné chování a budou ztraceny,
'     dojde-li k novému generování kódu.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    'Tato třída byla automaticky generována třídou StronglyTypedResourceBuilder
    'pomocí nástroje podobného aplikaci ResGen nebo Visual Studio.
    'Chcete-li přidat nebo odebrat člena, upravte souboru .ResX a pak znovu spusťte aplikaci ResGen
    's parametrem /str nebo znovu sestavte projekt aplikace Visual Studio.
    '''<summary>
    '''  Třída prostředků se silnými typy pro vyhledávání lokalizovaných řetězců atp.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute()>  _
    Friend Class Strings
        
        Private Shared resourceMan As Global.System.Resources.ResourceManager
        
        Private Shared resourceCulture As Global.System.Globalization.CultureInfo
        
        <Global.System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")>  _
        Friend Sub New()
            MyBase.New
        End Sub
        
        '''<summary>
        '''  Vrací instanci ResourceManager uloženou v mezipaměti použitou touto třídou.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Shared ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("TrackVideoExporter.Strings", GetType(Strings).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Potlačí vlastnost CurrentUICulture aktuálního vlákna pro všechna
        '''  vyhledání prostředků pomocí třídy prostředků se silnými typy.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Shared Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        '''<summary>
        '''  Vyhledá lokalizovaný řetězec podobný Accuracy.
        '''</summary>
        Friend Shared ReadOnly Property Accuracy() As String
            Get
                Return ResourceManager.GetString("Accuracy", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Vyhledá lokalizovaný řetězec podobný Dog Reading.
        '''</summary>
        Friend Shared ReadOnly Property DogReading() As String
            Get
                Return ResourceManager.GetString("DogReading", resourceCulture)
            End Get
        End Property

        '''<summary>
        '''  Vyhledá lokalizovaný řetězec podobný Pick-up.
        '''</summary>
        Friend Shared ReadOnly Property TrailPickup() As String
            Get
                Return ResourceManager.GetString("TrailPickup", resourceCulture)
            End Get
        End Property

        '''<summary>
        '''  Vyhledá lokalizovaný řetězec podobný FinalFind.
        '''</summary>
        Friend Shared ReadOnly Property FinalFind() As String
            Get
                Return ResourceManager.GetString("FinalFind", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Vyhledá lokalizovaný řetězec podobný of.
        '''</summary>
        Friend Shared ReadOnly Property ofPoints() As String
            Get
                Return ResourceManager.GetString("ofPoints", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Vyhledá lokalizovaný řetězec podobný points.
        '''</summary>
        Friend Shared ReadOnly Property points() As String
            Get
                Return ResourceManager.GetString("points", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Vyhledá lokalizovaný řetězec podobný Scoring.
        '''</summary>
        Friend Shared ReadOnly Property Scoring() As String
            Get
                Return ResourceManager.GetString("Scoring", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Vyhledá lokalizovaný řetězec podobný Speed.
        '''</summary>
        Friend Shared ReadOnly Property Speed() As String
            Get
                Return ResourceManager.GetString("Speed", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Vyhledá lokalizovaný řetězec podobný Total.
        '''</summary>
        Friend Shared ReadOnly Property Total() As String
            Get
                Return ResourceManager.GetString("Total", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Vyhledá lokalizovaný řetězec podobný Trail description.
        '''</summary>
        Friend Shared ReadOnly Property Trail_description() As String
            Get
                Return ResourceManager.GetString("Trail_description", resourceCulture)
            End Get
        End Property
    End Class
End Namespace
